# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias lsl='ls -lhp --time-style=long'

ulimit -c unlimited
